import mongoose from "mongoose";

const DiscoveryPageSchema = new mongoose.Schema(
  {
    // Page identification
    slug: {
      type: String,
      unique: true,
      required: true,
      trim: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
    },
    
    // Page type and category
    pageType: {
      type: String,
      enum: ["best-genre", "top-platform", "movies-like", "year-best", "highest-grossing", "trending", "custom"],
      required: true,
    },
    category: {
      type: String,
      enum: ["Bollywood", "Hollywood", "WebSeries", "OTT", "All"],
      default: "All",
    },
    
    // Query parameters for fetching movies
    queryParams: {
      genre: String,
      platform: String,
      year: Number,
      minRating: Number,
      sortBy: {
        type: String,
        enum: ["rating", "releaseYear", "boxOffice", "views"],
        default: "rating",
      },
      limit: {
        type: Number,
        default: 20,
      },
    },
    
    // Cached movie list (updated periodically)
    movies: [{
      _id: String,
      slug: String,
      movieTitle: String,
      releaseYear: Number,
      coverImage: String,
      backdropImage: String,
      rating: String,
      genres: [String],
      summary: String,
    }],
    
    // SEO metadata
    seo: {
      metaTitle: String,
      metaDescription: String,
      keywords: [String],
      ogImage: String,
    },
    
    // Content sections (AI-generated)
    sections: [{
      heading: String,
      content: String,
    }],
    
    // FAQ for schema markup
    faq: [{
      question: String,
      answer: String,
    }],
    
    // Stats
    stats: {
      views: { type: Number, default: 0 },
      lastViewed: Date,
    },
    
    // Status
    status: {
      type: String,
      enum: ["draft", "published", "archived"],
      default: "draft",
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    lastRefreshed: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

// Indexes for faster queries
DiscoveryPageSchema.index({ slug: 1 });
DiscoveryPageSchema.index({ pageType: 1 });
DiscoveryPageSchema.index({ status: 1 });
DiscoveryPageSchema.index({ "queryParams.genre": 1 });
DiscoveryPageSchema.index({ "queryParams.platform": 1 });

export default mongoose.models.DiscoveryPage || 
  mongoose.model("DiscoveryPage", DiscoveryPageSchema);
