// Internal Linking System - Auto linking for SEO ranking
// movie → actor → genre → OTT → similar movies
// model/InternalLink.js

import mongoose from "mongoose";

const InternalLinkSchema = new mongoose.Schema(
  {
    // Source page (from)
    sourceId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    sourceType: {
      type: String,
      enum: ["Article", "Celebrity", "Genre", "OTT", "DiscoveryPage", "CategoryPage"],
      required: true,
    },
    sourceSlug: {
      type: String,
      required: true,
      lowercase: true,
    },

    // Target page (to)
    targetId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    targetType: {
      type: String,
      enum: ["Article", "Celebrity", "Genre", "OTT", "DiscoveryPage", "CategoryPage"],
      required: true,
    },
    targetSlug: {
      type: String,
      required: true,
      lowercase: true,
    },

    // Link relationship type
    linkType: {
      type: String,
      enum: [
        "movie-to-actor",
        "movie-to-genre",
        "movie-to-ott",
        "movie-to-similar",
        "actor-to-filmography",
        "actor-to-movies",
        "genre-to-movies",
        "ott-to-movies",
        "discovery-to-movie",
        "category-to-movie",
        "page-to-page",
      ],
      required: true,
    },

    // Anchor text for the link
    anchorText: {
      type: String,
      required: true,
      maxlength: 100,
    },

    // Link context (where the link appears in the content)
    section: {
      type: String,
      enum: ["intro", "content", "related", "faq", "footer", "sidebar"],
      default: "content",
    },

    // SEO weight (priority for keyword ranking)
    seoWeight: {
      type: Number,
      min: 0,
      max: 100,
      default: 50, // 50% default weight
    },

    // Status
    status: {
      type: String,
      enum: ["active", "inactive"],
      default: "active",
    },

    // Click tracking
    clicks: {
      type: Number,
      default: 0,
    },
    ctr: {
      type: Number,
      default: 0,
    },

    // Auto-generated or manual
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
    indexes: [
      { sourceId: 1, sourceType: 1 },
      { targetId: 1, targetType: 1 },
      { linkType: 1 },
      { status: 1 },
      { seoWeight: -1 },
      { clicks: -1 },
    ],
  }
);

// Prevent duplicate links
InternalLinkSchema.index(
  { sourceId: 1, targetId: 1, linkType: 1 },
  { unique: true, sparse: true, name: "unique_internal_link" }
);

// Get all outgoing links from a page
InternalLinkSchema.statics.getOutgoingLinks = async function (
  sourceId,
  sourceType
) {
  return await this.find({
    sourceId,
    sourceType,
    status: "active",
  }).sort({ seoWeight: -1 });
};

// Get all incoming links to a page
InternalLinkSchema.statics.getIncomingLinks = async function (
  targetId,
  targetType
) {
  return await this.find({
    targetId,
    targetType,
    status: "active",
  }).sort({ seoWeight: -1 });
};

// Get links by type
InternalLinkSchema.statics.getLinksByType = async function (linkType) {
  return await this.find({ linkType, status: "active" });
};

// Update click count
InternalLinkSchema.methods.recordClick = function () {
  this.clicks += 1;
  return this.save();
};

export default mongoose.models.InternalLink ||
  mongoose.model("InternalLink", InternalLinkSchema);
