// Auto-generate Internal Links Utility
// lib/internal-links/generator.js
// Automatically create internal links for movie → actor, movie → genre, etc.

import InternalLink from "../../model/InternalLink";
import Article from "../../model/article";
import Celebrity from "../../model/celebrity";

/**
 * Generate links for a movie to its cast
 * movie → actor (80% SEO weight)
 */
export async function generateMovieToCastLinks(movieId, movieSlug, cast) {
  try {
    const links = [];

    for (const castMember of cast || []) {
      // Find celebrity by name
      const celebrity = await Celebrity.findOne({
        "heroSection.name": new RegExp(castMember.name, "i"),
      });

      if (celebrity) {
        const link = await InternalLink.create({
          sourceId: movieId,
          sourceType: "Article",
          sourceSlug: movieSlug,
          targetId: celebrity._id,
          targetType: "Celebrity",
          targetSlug: celebrity.slug,
          linkType: "movie-to-actor",
          anchorText: `${castMember.name} movies`,
          section: "content",
          seoWeight: 80, // High weight for cast links
          isAutoGenerated: true,
        });

        links.push(link);
      }
    }

    return links;
  } catch (error) {
    console.error("Error generating movie-to-cast links:", error);
    return [];
  }
}

/**
 * Generate links for a movie to similar movies
 * movie → similar movie (60% SEO weight)
 */
export async function generateMovieToSimilarLinks(movieId, movieSlug, similarMovies) {
  try {
    const links = [];

    for (const similarMovie of similarMovies || []) {
      const link = await InternalLink.create({
        sourceId: movieId,
        sourceType: "Article",
        sourceSlug: movieSlug,
        targetId: similarMovie._id || similarMovie,
        targetType: "Article",
        targetSlug: similarMovie.slug,
        linkType: "movie-to-similar",
        anchorText: `similar to ${similarMovie.movieTitle}`,
        section: "related",
        seoWeight: 60,
        isAutoGenerated: true,
      });

      links.push(link);
    }

    return links;
  } catch (error) {
    console.error("Error generating similar movie links:", error);
    return [];
  }
}

/**
 * Generate actor filmography links
 * actor → movies (70% SEO weight)
 */
export async function generateActorFilmographyLinks(actorId, actorSlug, movies) {
  try {
    const links = [];

    for (const movie of movies || []) {
      const link = await InternalLink.create({
        sourceId: actorId,
        sourceType: "Celebrity",
        sourceSlug: actorSlug,
        targetId: movie._id || movie,
        targetType: "Article",
        targetSlug: movie.slug,
        linkType: "actor-to-movies",
        anchorText: movie.movieTitle,
        section: "content",
        seoWeight: 70,
        isAutoGenerated: true,
      });

      links.push(link);
    }

    return links;
  } catch (error) {
    console.error("Error generating actor filmography links:", error);
    return [];
  }
}

/**
 * Generate discovery page to movies links
 * discovery → movie (50% SEO weight)
 */
export async function generateDiscoveryToMovieLinks(
  discoveryPageId,
  discoverySlug,
  movies,
  pageType
) {
  try {
    const links = [];

    for (const movie of movies || []) {
      const link = await InternalLink.create({
        sourceId: discoveryPageId,
        sourceType: "DiscoveryPage",
        sourceSlug: discoverySlug,
        targetId: movie._id || movie,
        targetType: "Article",
        targetSlug: movie.slug,
        linkType: "discovery-to-movie",
        anchorText: movie.movieTitle,
        section: "content",
        seoWeight: 50,
        isAutoGenerated: true,
      });

      links.push(link);
    }

    return links;
  } catch (error) {
    console.error("Error generating discovery-to-movie links:", error);
    return [];
  }
}

/**
 * Generate category page to movies links
 * category → movie (50% SEO weight)
 */
export async function generateCategoryToMovieLinks(
  categoryPageId,
  categorySlug,
  movies
) {
  try {
    const links = [];

    for (const movie of movies || []) {
      const link = await InternalLink.create({
        sourceId: categoryPageId,
        sourceType: "CategoryPage",
        sourceSlug: categorySlug,
        targetId: movie._id || movie,
        targetType: "Article",
        targetSlug: movie.slug,
        linkType: "category-to-movie",
        anchorText: movie.movieTitle,
        section: "content",
        seoWeight: 50,
        isAutoGenerated: true,
      });

      links.push(link);
    }

    return links;
  } catch (error) {
    console.error("Error generating category-to-movie links:", error);
    return [];
  }
}

/**
 * Generate cross-pSEO page links
 * movie main page → sub pages (40% SEO weight)
 */
export async function generatePSEOPageCrossLinks(movieId, movieSlug, subPages) {
  try {
    const links = [];

    // Link main page to sub pages
    for (const subPage of subPages || []) {
      const link = await InternalLink.create({
        sourceId: movieId,
        sourceType: "Article",
        sourceSlug: movieSlug,
        targetId: subPage._id,
        targetType: "Article",
        targetSlug: `${movieSlug}-${subPage.slug}`,
        linkType: "page-to-page",
        anchorText: `${subPage.pageType.replace(/-/g, " ")} – Read More`,
        section: "related",
        seoWeight: 40,
        isAutoGenerated: true,
      });

      links.push(link);
    }

    return links;
  } catch (error) {
    console.error("Error generating pSEO cross links:", error);
    return [];
  }
}

/**
 * Generate all internal links for a movie
 * Comprehensive linking: cast + similar + sub-pages
 */
export async function generateAllMovieLinks(movieId, movieSlug, movieData) {
  try {
    const allLinks = [];

    // Generate cast links
    const castLinks = await generateMovieToCastLinks(
      movieId,
      movieSlug,
      movieData.cast
    );
    allLinks.push(...castLinks);

    // Generate similar movie links
    const similarLinks = await generateMovieToSimilarLinks(
      movieId,
      movieSlug,
      movieData.relatedMovies
    );
    allLinks.push(...similarLinks);

    return {
      success: true,
      linksCreated: allLinks.length,
      details: {
        castLinks: castLinks.length,
        similarMovieLinks: similarLinks.length,
      },
      data: allLinks,
    };
  } catch (error) {
    console.error("Error generating all movie links:", error);
    return {
      success: false,
      message: error.message,
    };
  }
}

/**
 * Get internal links for rendering in templates
 * Returns links with proper context for template rendering
 */
export async function getLinksForRendering(sourceId, sourceType) {
  try {
    const links = await InternalLink.getOutgoingLinks(sourceId, sourceType);

    // Group by link type
    const grouped = {
      "movie-to-actor": links.filter((l) => l.linkType === "movie-to-actor"),
      "movie-to-similar": links.filter((l) => l.linkType === "movie-to-similar"),
      "page-to-page": links.filter((l) => l.linkType === "page-to-page"),
      "actor-to-movies": links.filter((l) => l.linkType === "actor-to-movies"),
    };

    return {
      success: true,
      totalLinks: links.length,
      grouped,
      all: links,
    };
  } catch (error) {
    console.error("Error getting links for rendering:", error);
    return {
      success: false,
      message: error.message,
    };
  }
}
